import Head from 'next/head';

import useFetch from '../hooks/useFetch';
import Link from 'next/link';
import { gql } from '@apollo/client';

const REVIEWS = gql`
  query GetReviews {
    reviews {
      id
      title
      rating
      body
      categories {
        id
        name
      }
    }
  }
`;

export default function Home() {
  // Getting data from rest api
  const { loading, error, data } = useFetch('http://localhost:1337/reviews');

  // //Getting data from graphql
  // const { loading, error, data } = useQuery(REVIEWS);

  if (loading) return <p>loading</p>;
  if (error) return <p>Error :(</p>;

  console.log(loading, error, data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        {/** For graphql */}
        {/* {data?.reviews?.map((review) => ( */}
        {data?.map((review) => (
          <div key={review.id} className='review-card'>
            <div className='rating'>{review.rating} </div>
            <h2>{review.title}</h2>

            {review?.categories.map((c) => (
              <small key={c.id}>{c.name}</small>
            ))}

            <p>{review.body.substring(0, 200)}...</p>

            <Link href={`/reviews/${review.id}`}>Read more</Link>
          </div>
        ))}
      </div>
    </div>
  );
}
