import Head from 'next/head';

import useFetch from '../hooks/useFetch';
import Link from 'next/link';
import { gql } from '@apollo/client';
import Loader from 'react-loader-spinner';

const REVIEWS = gql`
  query GetReviews {
    reviews {
      id
      title
      rating
      body
      categories {
        id
        name
      }
    }
  }
`;

export default function Home() {
  // Getting data from rest api
  // const { loading, error, data } = useFetch('http://localhost:1337/reviews');
  const { loading, error, data } = useFetch(
    `${process.env.NEXT_PUBLIC_STRAPI_API_URL}/reviews`
  );

  // //Getting data from graphql
  // const { loading, error, data } = useQuery(REVIEWS);

  if (loading)
    return (
      <div className='spinner-poistion'>
        <Loader
          type='Oval'
          color='#8e2ad6'
          height={100}
          width={100}
          timeout={3000} //3 secs
        />
      </div>
    );
  if (error) return <p>Error :(</p>;

  return (
    <div>
      <Head>
        <title>Trendshots</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/trending.png' />
      </Head>

      <div className='header-content'>
        <h1 className='site-title'>Trendshots Daily</h1>
        <br />
        <p className='site-content'>
          3 Min reads that are fun, insightful and easy to understand. This is
          Finshots as you know it.
        </p>
      </div>

      <div className='row'>
        {/** For graphql */}
        {/* {data?.reviews?.map((review) => ( */}
        {data?.map((review) => (
          <div key={review.id} className='review-card'>
            {/* Show with stars - do it later */}
            {/* <div className='rating'>{review.rating} </div> */}
            <h2>{review.title}</h2>

            {/* {review?.categories.map((c) => (
              <small key={c.id}>{c.name}</small>
            ))} */}

            <p>{review.body.substring(0, 200)}...</p>

            <Link href={`/reviews/${review.id}`}>Read more</Link>
          </div>
        ))}
      </div>
    </div>
  );
}
